### ISSUE TITLE
Remove gcc11 pin

### ISSUE THREAD

**Issue by johnlees** [conda-forge/mandrake-feedstock#15]
When pybind11 fix releases

**Comment by jakirkham** [comment]
Think we can do this now. In pybind11's 2.12.0 release, they included this fix: https://github.com/pybind/pybind11/commit/3414c56b6c7c521d868c9a137ca2ace2e26b5b2e

We included that release in conda-forge some time ago: https://github.com/conda-forge/pybind11-feedstock/pull/94

So would just drop this `use_local: true` line and [re-render]( https://conda-forge.org/docs/maintainer/updating_pkgs/#rerendering-feedstocks ):

https://github.com/conda-forge/mandrake-feedstock/blob/cb962de49527c0f8cdb11054bfddbbfb44366e12/.ci_support/migrations/cuda120.yaml#L5-L8
